# Basic PCGR configuration options (TOML).

[tumor_only]
## Variant filtering applied for option --tumor_only = true in pcgr.py
## Several filters can be configured, all as a means to minimize the proportion of germline calls in the raw set derived from tumor-only calling

## Exclude variants (SNVs/InDels) with minor allele frequency above the following population-specific thresholds
## 1000 Genomes Project - WGS data
maf_onekg_eur = 0.002
maf_onekg_amr = 0.002
maf_onekg_afr = 0.002
maf_onekg_sas = 0.002
maf_onekg_eas = 0.002
maf_onekg_global = 0.002

## exclude variants with minor allele frequency above the following population-specific thresholds
## gnomAD - WES data
maf_gnomad_nfe = 0.002
maf_gnomad_amr = 0.002
maf_gnomad_afr = 0.002
maf_gnomad_asj = 0.002
maf_gnomad_sas = 0.002
maf_gnomad_eas = 0.002
maf_gnomad_fin = 0.002
maf_gnomad_oth = 0.002
maf_gnomad_global = 0.002

## Exclude variants occurring in PoN (panel of normals, if provided as VCF)
exclude_pon = true

## Exclude likely homozygous germline variants (100% allelic fraction for alternate allele in tumor, very unlikely somatic event)
exclude_likely_hom_germline = false

## Exclude likely heterozygous germline variants
## Must satisfy i) 40-60 % allelic fraction for alternate allele in tumor sample, ii) present in dbSNP + gnomAD, ii) not existing as somatic event in COSMIC/TCGA
## Note that the application of this filter may be suboptimal for very impure tumors or variants affected by CNAs etc (under these circumstances, the allelic fraction
## will be skewed (see e.g. discussion in PMID:29249243)
exclude_likely_het_germline = false

## Exclude variants found in dbSNP (only those that are NOT found in ClinVar(somatic origin)/DoCM/TCGA/COSMIC)
exclude_dbsnp_nonsomatic = false

## exclude all non-exonic variants
exclude_nonexonic = true

[allelic_support]
## Specify INFO tags in input VCF that denotes depth/allelic fraction in tumor and normal sample
## An additional tag that denotes call confidence (call_conf_tag) can also be specified, which will
## be used for exploration in the global variant browser. Note that 'tumor_dp_tag' must be of
## Type=Integer, and 'tumor_af_tag' must be of Type=Float (similarly for normal sample)
tumor_dp_tag = "TDP"
tumor_af_tag = "TVAF"
control_dp_tag = ""
control_af_tag = ""
call_conf_tag = "TAL"

[visual]
## Choose visual theme of (rmarkdown) report, any of: "default", "cerulean", "journal", "flatly", "readable", "spacelab", "united", "cosmo", "lumen", "paper", "sandstone", "simplex", or "yeti" (https://bootswatch.com/)
report_theme = "default"

[custom_tags]
## list VCF info tags that should be present in JSON and TSV output
## tags should be comma separated, i.e. custom_tags = "MUTECT2_FILTER,STRELKA_FILTER"
custom_tags = ""

[other]
## list/do not list noncoding variants
list_noncoding = true
## VEP/vcfanno processing options
n_vcfanno_proc = 4
n_vep_forks = 4
## Customise the order of criteria used to pick the primary transcript in VEP (see https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_pick_order)
vep_pick_order = "canonical,appris,biotype,ccds,rank,tsl,length,mane"
## omit intergenic variants during VEP processing
vep_skip_intergenic = false
## generate a MAF for input VCF using https://github.com/mskcc/vcf2maf
vcf2maf = true
